name: RandomSpawn
version: "1.3"
author: IncinerateZ
main: tech.incineratez.randomspawn.RandomSpawn
description: Random Spawn Plugin

commands:
  rtp:
    description: Default command for Random Spawn.